#!/usr/bin/env python3
"""
indexSON.py

Builds a lightweight index.json file from locally stored JacSON profile JSON files.

Expected local structure:
    ./profiles/<semester_code>/<full_course_code>.json

Example:
    ./profiles/7620/MGTS1301-20352-7620.json

Output:
    ./profiles/index.json

This script does NOT hit any remote servers.
It reads only from the local ./profiles/ directory.

Compatible with profiles generated by both the original JacSON scraper
and the enriched Sean Smith / UQBS scraper (jacson.py v2+).
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


# =============================================================================
# CONFIGURATION
# =============================================================================

# --- For ./scripts/ directory run ---
SCRIPT_DIR = os.path.abspath(os.path.dirname(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
PROFILES_DIR = os.path.join(PROJECT_ROOT, "profiles")
OUTPUT_FILE = os.path.join(PROJECT_ROOT, "profiles", "index.json")
INDEX_VERSION = "1.1"

# --- For root directory run ---
# BASE_DIR = os.path.abspath(os.path.dirname(__file__))
# PROFILES_DIR = os.path.join(BASE_DIR, "profiles")
# OUTPUT_FILE = os.path.join(BASE_DIR, "index.json")
# INDEX_VERSION = "1.1"


# =============================================================================
# HELPERS
# =============================================================================

def safe_str(value: Any) -> str:
    """Return a clean string, or an empty string if value is None."""
    if value is None:
        return ""
    return str(value).strip()


def get_prefix(course_code: str) -> str:
    """Extract alphabetic prefix from a course code, e.g. MGTS1301 -> MGTS."""
    prefix = []
    for ch in course_code:
        if ch.isalpha():
            prefix.append(ch)
        else:
            break
    return "".join(prefix)


def get_course_coordinator(course_contacts: Any) -> tuple[Optional[str], Optional[str]]:
    """
    Return the first matching course coordinator name/email from course_contacts.

    Compatible with both scraper versions:
      - Original JacSON: contacts have 'role_slug' field
      - Enriched scraper: contacts have 'role_slug' generated inline

    Preferred match order:
    1. role_slug == "course_coordinator"
    2. role text contains "course coordinator" (case-insensitive)
    """
    if not isinstance(course_contacts, list):
        return None, None

    # First preference: role_slug
    for contact in course_contacts:
        if not isinstance(contact, dict):
            continue
        if safe_str(contact.get("role_slug")) == "course_coordinator":
            return (
                safe_str(contact.get("name")) or None,
                safe_str(contact.get("email")) or None,
            )

    # Second preference: role text
    for contact in course_contacts:
        if not isinstance(contact, dict):
            continue
        role = safe_str(contact.get("role")).lower()
        if "course coordinator" in role:
            return (
                safe_str(contact.get("name")) or None,
                safe_str(contact.get("email")) or None,
            )

    return None, None


def get_all_staff(course_contacts: Any, course_staff: Any) -> List[Dict[str, Any]]:
    """
    Return a unified list of all staff from both course_contacts and course_staff.
    Used to surface teaching staff count in the index.
    """
    staff_list: List[Dict[str, Any]] = []
    seen: set = set()

    def _add(name: str, role: str, email: str):
        key = (name, role)
        if key not in seen and (name or role):
            seen.add(key)
            staff_list.append({"name": name, "role": role, "email": email})

    if isinstance(course_contacts, list):
        for c in course_contacts:
            if isinstance(c, dict):
                _add(
                    safe_str(c.get("name")),
                    safe_str(c.get("role")),
                    safe_str(c.get("email")),
                )

    if isinstance(course_staff, list):
        for s in course_staff:
            if isinstance(s, dict):
                _add(
                    safe_str(s.get("name")),
                    safe_str(s.get("role")),
                    safe_str(s.get("email")),
                )

    return staff_list


def _get_indicators(assessment: Any) -> List[str]:
    """
    Return a flat list of special_indicator_text strings for an assessment item.

    Handles both:
      - assessments list (from summary table, used in original JacSON)
      - assessment_details list (from detail sections, used in enriched scraper)
    """
    texts: List[str] = []
    indicators = assessment.get("special_indicators", [])
    if not isinstance(indicators, list):
        return texts
    for ind in indicators:
        if isinstance(ind, dict):
            text = safe_str(ind.get("special_indicator_text"))
            if text:
                texts.append(text)
        elif isinstance(ind, str) and ind:
            texts.append(ind)
    return texts


def _get_all_assessments(course_data: Dict[str, Any]) -> List[Any]:
    """
    Return the best available assessment list from a course profile.

    Priority:
      1. "assessments"        — summary list (original JacSON field)
      2. "assessment_details" — detail list  (enriched scraper field)
    Falls back to an empty list if neither exists.
    """
    assessments = course_data.get("assessments")
    if isinstance(assessments, list) and assessments:
        return assessments
    details = course_data.get("assessment_details")
    if isinstance(details, list) and details:
        return details
    return []


def has_group_assessment(course_data: Dict[str, Any]) -> bool:
    """
    True if any assessment has special_indicator_text == "Team or group-based".
    Checks both assessments and assessment_details lists.
    """
    for assessment in _get_all_assessments(course_data):
        if not isinstance(assessment, dict):
            continue
        for text in _get_indicators(assessment):
            if text == "Team or group-based":
                return True
    return False


def has_hurdle(course_data: Dict[str, Any]) -> bool:
    """
    True if any assessment has any non-empty special_indicator_text.
    Checks both assessments and assessment_details lists.
    """
    for assessment in _get_all_assessments(course_data):
        if not isinstance(assessment, dict):
            continue
        if _get_indicators(assessment):
            return True
    return False


def get_attendance(course_data: Dict[str, Any]) -> Optional[str]:
    """
    Return the attendance field from a profile, handling both field name variants:
      - "attendance"      (original JacSON)
      - "attendance_mode" (enriched scraper)
    """
    val = course_data.get("attendance") or course_data.get("attendance_mode")
    return safe_str(val) or None


def build_display_label(course_code: str, course_title: str, study_period: str) -> str:
    """
    Build a dropdown-friendly label:
        MINE1234: Course Title Here (Sem 1 2026)
    """
    course_code = safe_str(course_code)
    course_title = safe_str(course_title)
    study_period = safe_str(study_period)
    if study_period:
        return f"{course_code}: {course_title} ({study_period})"
    return f"{course_code}: {course_title}"


def make_json_path(full_course_code: str, semester_code: str) -> str:
    """Return repo-relative JSON path."""
    return f"profiles/{semester_code}/{full_course_code}.json"


def make_json_url(full_course_code: str, semester_code: str) -> str:
    """Return hosted GitHub Pages JSON URL."""
    return f"https://uq-course-profiles.github.io/jacson/profiles/{semester_code}/{full_course_code}.json"


def load_json_file(filepath: str) -> Optional[Dict[str, Any]]:
    """Load a JSON file safely."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict):
            return data
        print(f"Skipping non-object JSON: {filepath}")
        return None
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return None


# =============================================================================
# INDEX BUILDING
# =============================================================================

def build_index_record(course_data: Dict[str, Any]) -> Dict[str, Any]:
    """Convert one full course JSON object into one index record."""
    full_course_code = safe_str(course_data.get("full_course_code"))
    course_code      = safe_str(course_data.get("course_code"))
    class_code       = safe_str(course_data.get("class_code"))
    semester_code    = safe_str(course_data.get("semester_code"))
    course_title     = safe_str(course_data.get("course_title"))
    study_period     = safe_str(course_data.get("study_period"))
    study_level      = safe_str(course_data.get("study_level")) or None
    units            = safe_str(course_data.get("units")) or None
    location         = safe_str(course_data.get("location")) or None
    attendance       = get_attendance(course_data)
    url              = safe_str(course_data.get("url"))
    scraped_at       = safe_str(course_data.get("scraped_at")) or None

    learning_outcomes   = course_data.get("learning_outcomes", [])
    learning_activities = course_data.get("learning_activities", [])
    course_contacts     = course_data.get("course_contacts", [])
    course_staff        = course_data.get("course_staff", [])

    coordinator_name, coordinator_email = get_course_coordinator(course_contacts)
    all_staff = get_all_staff(course_contacts, course_staff)
    assessments = _get_all_assessments(course_data)

    record = {
        "id":                         full_course_code,
        "full_course_code":           full_course_code,
        "course_code":                course_code,
        "course_title":               course_title,
        "class_code":                 class_code,
        "semester_code":              semester_code,
        "study_period":               study_period,
        "study_level":                study_level,
        "units":                      units,
        "url":                        url,
        "json_path":                  make_json_path(full_course_code, semester_code),
        "json_url":                   make_json_url(full_course_code, semester_code),
        "prefix":                     get_prefix(course_code),
        "location":                   location,
        "attendance":                 attendance,
        "display_label":              build_display_label(course_code, course_title, study_period),
        "course_coordinator_name":    coordinator_name,
        "course_coordinator_email":   coordinator_email,
        "staff_count":                len(all_staff),
        "learning_outcomes_count":    len(learning_outcomes) if isinstance(learning_outcomes, list) else 0,
        "assessments_count":          len(assessments),
        "learning_activities_count":  len(learning_activities) if isinstance(learning_activities, list) else 0,
        "group_assessment":           has_group_assessment(course_data),
        "hurdle":                     has_hurdle(course_data),
        "scraped_at":                 scraped_at,
    }

    return record


def discover_profile_files(profiles_dir: str) -> List[str]:
    """Recursively find all .json profile files under ./profiles, excluding index.json."""
    json_files: List[str] = []

    if not os.path.isdir(profiles_dir):
        print(f"Profiles directory not found: {profiles_dir}")
        return json_files

    for root, _, files in os.walk(profiles_dir):
        for filename in files:
            if not filename.lower().endswith(".json"):
                continue
            full_path = os.path.join(root, filename)
            # Skip the index itself
            if os.path.abspath(full_path) == os.path.abspath(OUTPUT_FILE):
                continue
            json_files.append(full_path)

    json_files.sort()
    return json_files


def build_index(profiles_dir: str) -> Dict[str, Any]:
    """Build the full wrapped index object from all local profile files."""
    profile_files = discover_profile_files(profiles_dir)
    courses: List[Dict[str, Any]] = []

    for filepath in profile_files:
        course_data = load_json_file(filepath)
        if not course_data:
            continue

        full_course_code = safe_str(course_data.get("full_course_code"))
        course_code      = safe_str(course_data.get("course_code"))
        semester_code    = safe_str(course_data.get("semester_code"))

        if not full_course_code or not course_code or not semester_code:
            print(f"Skipping incomplete profile (missing key identifiers): {filepath}")
            continue

        try:
            record = build_index_record(course_data)
            courses.append(record)
        except Exception as e:
            print(f"Error building index record for {filepath}: {e}")

    # Sort: newest semester first, then course code, then class code
    courses.sort(
        key=lambda x: (
            safe_str(x.get("semester_code")),
            safe_str(x.get("course_code")),
            safe_str(x.get("class_code")),
        ),
        reverse=True,
    )

    unique_semesters = sorted(
        {safe_str(c.get("semester_code")) for c in courses if safe_str(c.get("semester_code"))},
        reverse=True,
    )
    unique_prefixes = sorted(
        {safe_str(c.get("prefix")) for c in courses if safe_str(c.get("prefix"))}
    )

    index_data = {
        "generated_at":    datetime.now(timezone.utc).astimezone().isoformat(),
        "version":         INDEX_VERSION,
        "source_directory": "./profiles",
        "output_file":     "./profiles/index.json",
        "total_courses":   len(courses),
        "total_semesters": len(unique_semesters),
        "total_prefixes":  len(unique_prefixes),
        "courses":         courses,
    }

    return index_data


def save_index(index_data: Dict[str, Any], output_file: str) -> None:
    """Write index.json to disk."""
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(index_data, f, ensure_ascii=False, indent=4)
    print(f"Saved index to {output_file}")


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    print("Building JacSON local index from ./profiles ...")
    index_data = build_index(PROFILES_DIR)
    save_index(index_data, OUTPUT_FILE)
    print(
        f"Done. Indexed {index_data['total_courses']} course profiles across "
        f"{index_data['total_semesters']} semester(s)."
    )


if __name__ == "__main__":
    main()
