name: Run JacSON Scraper

on:
  schedule:
    - cron: '0 17 * * *'  # 3:00 AM AEST (UTC+10 → UTC = 17:00)
  workflow_dispatch:      # Allows manual runs from the GitHub UI

jobs:
  run-jacson:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run JacSON full scraper (auto mode)
        run: python scripts/scraper_runner-GithubAuto.py
